In [23]:
#import necesary libaries
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [24]:
#load the dataset
data=pd.read_csv('Maternal Health Risk Data Set.csv')

In [25]:
data.head()

   Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86  high risk
1   35         140           90  13.0      98.0         70  high risk
2   29          90           70   8.0     100.0         80  high risk
3   30         140           85   7.0      98.0         70  high risk
4   35         120           60   6.1      98.0         76   low risk

In [26]:
data.columns

Index(['Age', 'SystolicBP', 'DiastolicBP', 'BS', 'BodyTemp', 'HeartRate',
       'RiskLevel'],
      dtype='object')

In [27]:
y=data['RiskLevel']

In [28]:
print(y)

0       high risk
1       high risk
2       high risk
3       high risk
4        low risk
          ...
1009    high risk
1010    high risk
1011    high risk
1012    high risk
1013     mid risk
Name: RiskLevel, Length: 1014, dtype: object

In [29]:
#RiskLevel will be the main factor of this algorthim

In [30]:
newx=data.drop('RiskLevel', axis='columns')

In [31]:
newx

      Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate
0      25         130           80  15.0      98.0         86
1      35         140           90  13.0      98.0         70
2      29          90           70   8.0     100.0         80
3      30         140           85   7.0      98.0         70
4      35         120           60   6.1      98.0         76
...   ...         ...          ...   ...       ...        ...
1009   22         120           60  15.0      98.0         80
1010   55         120           90  18.0      98.0         60
1011   35          85           60  19.0      98.0         86
1012   43         120           90  18.0      98.0         70
1013   32         120           65   6.0     101.0         76

[1014 rows x 6 columns]

In [32]:
X_train,X_test,y_train, y_test=train_test_split(newx,y,test_size=.2)

In [33]:
X_train

     Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate
689   40         160          100  19.0      98.0         77
149   37         120           90  11.0      98.0         88
76    22          85           60   6.9      98.0         76
264   22         100           65   6.9      98.0         70
750   32         120           65   6.0     101.0         76
..   ...         ...          ...   ...       ...        ...
521   23         120           90   7.5      98.0         70
511   25         120           90   7.5     101.0         80
723   29          90           70   6.7      98.0         80
246   18         100           70   6.8      98.0         76
185   55         100           65   6.1      98.0         66

[811 rows x 6 columns]

In [34]:
y_train

689    high risk
149    high risk
76      mid risk
264     low risk
750     mid risk
         ...
521     low risk
511     low risk
723     mid risk
246     low risk
185     low risk
Name: RiskLevel, Length: 811, dtype: object

In [35]:
X_test

     Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate
388   23         120           70   7.8      98.0         70
609   22         120           85   7.5      98.0         88
492   29         130           70   7.9      98.0         78
23    18          90           60   7.5      98.0         70
666   21          90           50   6.5      98.0         60
..   ...         ...          ...   ...       ...        ...
166   40         160          100  19.0      98.0         77
958   37         120           90  11.0      98.0         88
587   28          90           60   7.5      98.0         82
892   17          90           60   7.9     101.0         76
114   63         140           90  15.0      98.0         90

[203 rows x 6 columns]

In [36]:
y_test

388     low risk
609     low risk
492     mid risk
23      low risk
666     low risk
         ...
166    high risk
958    high risk
587     mid risk
892     low risk
114    high risk
Name: RiskLevel, Length: 203, dtype: object

In [37]:
#Initailize the logisitc regression model
model= LogisticRegression()

In [38]:
#Fit the model to the training data 
model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [39]:
#Make predictions on the test data
y_pred=model.predict(X_test)

In [40]:
#Model will make predictions on data based on how it was trained
#Acurracy at about 60% of the probability that the RiskFactor will be high risk for the expectant mothers

In [41]:
#Evaluate the model's accuracy
accuracy=accuracy_score(y_test,y_pred)
print('Accuracy',accuracy)

Accuracy 0.6059113300492611